# Top-level items
[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2

[[main]]
  identifier = "join"
  name = "Join Us"
  url = "/join/"
  weight = 3

[[main]]
  identifier = "sections"
  name = "Sections"
  url = "/sections/"
  weight = 4

[[main]]
  identifier = "committee"
  name = "Committee"
  url = "/committee/"
  weight = 4.5

[[main]]
  identifier = "leaders"
  name = "Leaders & Volunteers"
  url = "/leaders/"
  weight = 5

[[main]]
  identifier = "events"
  name = "Events"
  url = "/events/"
  weight = 5.5

[[main]]
  identifier = "news"
  name = "News"
  url = "/news/"
  weight = 6

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 7

# Events dropdown items
[[main]]
  name = "ANZAC Day March"
  parent = "events"
  url = "/anzac-day-march/"
  weight = 5.49

[[main]]
  name = "Mango Fundraiser"
  parent = "events"
  url = "/mango-fundraiser/"
  weight = 5.50

[[main]]
  name = "Bardon Mayfair"
  parent = "events"
  url = "/bardon-mayfair/"
  weight = 5.51

[[main]]
  name = "Fair on the Green"
  parent = "events"
  url = "/fair-on-the-green/"
  weight = 5.52

[[main]]
  name = "Operation NightHawk"
  parent = "events"
  url = "/operation-nighthawk/"
  weight = 5.53

[[main]]
  name = "Pizza and Paddle"
  parent = "events"
  url = "/pizza-and-paddle/"
  weight = 5.54

# Join Us dropdown items
[[main]]
  name = "How to Join"
  parent = "join"
  url = "/join/how-to-join/"
  weight = 3.1

[[main]]
  name = "Fees & Costs"
  parent = "join"
  url = "/join/fees/"
  weight = 3.2

[[main]]
  name = "Uniforms"
  parent = "join"
  url = "/join/uniforms/"
  weight = 3.3

[[main]]
  name = "Come and Try"
  parent = "join"
  url = "/join/come-and-try/"
  weight = 3.4

[[main]]
  name = "New Family FAQs"
  parent = "join"
  url = "/join/faqs/"
  weight = 3.5

[[main]]
  name = "Taking a Break or Finishing Up"
  parent = "join"
  url = "/join/taking-a-break/"
  weight = 3.6

# Sections dropdown items
[[main]]
  name = "Joeys (6-8)"
  parent = "sections"
  url = "/sections/joeys/"
  weight = 1

[[main]]
  name = "Cubs (8-11)"
  parent = "sections"
  url = "/sections/cubs/"
  weight = 2

[[main]]
  name = "Scouts (11-15)"
  parent = "sections"
  url = "/sections/scouts/"
  weight = 3

[[main]]
  name = "Venturers (14-18)"
  parent = "sections"
  url = "/sections/venturers/"
  weight = 4

# Leaders & Volunteers dropdown items
[[main]]
  name = "Our Leaders"
  parent = "leaders"
  url = "/leaders/our-leaders/"
  weight = 5.1

[[main]]
  name = "Volunteering"
  parent = "leaders"
  url = "/leaders/volunteering/"
  weight = 5.2
